<a href="https://colab.research.google.com/github/vtoriano/exerc-cio_cd_1/blob/master/pandas_intro_ex2_(5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade 2 — Exercícios de Limpeza, Transformação e Agrupamento de Dados

Responda as perguntas abaixo usando o dataset **emendas_tratamento.parquet**. o dataset pode ser baixado em https://drive.google.com/file/d/19ydA23-eboyiKxN29JL1EQWW4CplTiKg/view?usp=sharing.

Cada resposta deve ter:
- Uma célula de **código** com a solução
- Uma célula de **texto** (Markdown) com a sua interpretação do resultado

---
## Passo 0 — Importar pandas e carregar os dados

In [12]:
import pandas as pd
df = pd.read_parquet ("https://drive.google.com/uc?export=download&id=19ydA23-eboyiKxN29JL1EQWW4CplTiKg")

## 1) Filtre apenas as emendas do ano de **2022** e mostre as 30 primeiras linhas. Em seguida responda: Quanta emendas foram registradas em 2022?

In [40]:
df_2022 = df[df['Ano da Emenda'] == 2022]
print (df_2022.shape[0])

0

## 2) Filtre as emendas da região **Norte** que tenham `Valor Empenhado` maior que **500.000** e mostre as 5 primeiras linhas. Em seguida, responda: quantas emendas atendem a esses duas condições ao mesmo tempo?

In [41]:
df_norte = df[(df['Região'] == 'Norte') & (df['Valor Empenhado'] > 50000)]
df_norte.head()

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1,Saldo a Pagar
1,Sem informação,2014,Emenda Individual - Transferências com Finalid...,-1.0,desconhecido,S/I,SANTA ISABEL DO PARÁ - PA,1506500,SANTA ISABEL DO PARÁ,1500000,...,0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,487500.0,0.0,0.0,0.0,487500.0,0.0,Sem informação,487500.0
18,Sem informação,2014,Emenda Individual - Transferências com Finalid...,-1.0,desconhecido,S/I,MÂNCIO LIMA - AC,1200336,MÂNCIO LIMA,1200000,...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,616610.0,0.0,0.0,0.0,0.0,616610.0,Sem informação,616610.0
31,Sem informação,2014,Emenda Individual - Transferências com Finalid...,-1.0,desconhecido,S/I,PORTO WALTER - AC,1200393,PORTO WALTER,1200000,...,0,IMPLEMENTACAO DE INFRAESTRUTURA BASICA NOS MUN...,300000.0,0.0,0.0,0.0,0.0,300000.0,Sem informação,300000.0
32,Sem informação,2014,Emenda Individual - Transferências com Finalid...,-1.0,desconhecido,S/I,CASTANHAL - PA,1502400,CASTANHAL,1500000,...,0,INFRAESTRUTURA PARA A EDUCACAO BASICA - DESPES...,150000.0,0.0,0.0,0.0,150000.0,0.0,Sem informação,150000.0
51,Sem informação,2014,Emenda Individual - Transferências com Finalid...,-1.0,desconhecido,S/I,RIO MARIA - PA,1506161,RIO MARIA,1500000,...,0,ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...,300000.0,0.0,0.0,0.0,0.0,300000.0,Sem informação,300000.0

## 3) Filtre as emendas que são do estado de **SÃO PAULO** ou do estado do **RIO DE JANEIRO** e mostre quantas linhas cada estado possui. Em seguida, responda: Qual dos dois estados possui mais emendas e quantas são?

In [55]:
sp_rj = df[df['UF'].isin(['SÃO PAULO', 'RIO DE JANEIRO'])]
print(sp_rj['UF'].value_counts())

UF
SÃO PAULO         10435
RIO DE JANEIRO     6988
Name: count, dtype: int64

## 4) Na coluna `Código da Emenda`, substitua todos os valores `"Sem informação"` por `"Não disponível"`. Mostre a contagem de valores únicos da coluna antes e depois da substituição.

In [20]:
df['Código da Emenda'] = df['Código da Emenda'].replace('sem informação', 'não disponivel')
print(df['Código da Emenda'].value_counts())

Código da Emenda
Sem informação    17808
202341820007          2
202336610004          2
201833870003          2
201833870004          2
                  ...
201921520003          1
201921520002          1
201921520001          1
201930530018          1
201921520008          1
Name: count, Length: 70731, dtype: int64

## 5) Na coluna `Nome Função`, transforme todos os valores para que fiquem em letras maiúsculas. Confirme a alteração mostrando os valores únicos da coluna.

In [24]:
df['Nome Função'] = df['Nome Função'].str.upper()
print(df['Nome Função'].unique())

['URBANISMO' 'COMÉRCIO E SERVIÇOS' 'SAÚDE' 'EDUCAÇÃO' 'AGRICULTURA'
 'ASSISTÊNCIA SOCIAL' 'DESPORTO E LAZER' 'DEFESA NACIONAL' 'SANEAMENTO'
 'DIREITOS DA CIDADANIA' 'GESTÃO AMBIENTAL' 'CULTURA'
 'CIÊNCIA E TECNOLOGIA' 'SEGURANÇA PÚBLICA' 'ORGANIZAÇÃO AGRÁRIA'
 'COMUNICAÇÕES' 'ADMINISTRAÇÃO' 'HABITAÇÃO' 'INDÚSTRIA' 'TRABALHO'
 'MÚLTIPLO' 'TRANSPORTE' 'PREVIDÊNCIA SOCIAL' 'ENCARGOS ESPECIAIS'
 'RELAÇÕES EXTERIORES' 'ENERGIA' 'ESSENCIAL À JUSTIÇA']

## 6) Verifique quantas linhas duplicadas existem no dataset. Em seguida, remova as duplicatas e mostre quantas linhas sobraram.

In [56]:
print(f'Linhas dupicadas: {df.duplicated().sum()}')
df = df.drop_duplicates()
print(f'Linhas após remoção: {len(df)}')

Linhas dupicadas: 63
Linhas após remoção: 88596

## 7) Remova duplicatas considerando apenas as colunas `Código da Emenda` e `Município`. Quantas linhas sobraram? O resultado é diferente de quando removemos duplicatas do DataFrame inteiro?

In [28]:
df_novo = df.drop_duplicates(subset=['Código da Emenda', 'Município'])
df_novo.shape[0]

75744

## 8) Identifique quais colunas possuem valores nulos e quantos nulos cada uma tem. Em seguida, responda: qual é a coluna que possui maior número de valores nulos e quantos são?

In [29]:
df_nulos = df.isnull().sum()
df_nulos

Código da Emenda                          0
Ano da Emenda                             0
Tipo de Emenda                            0
Código do Autor da Emenda             15961
Nome do Autor da Emenda               15961
Número da emenda                          0
Localidade de aplicação do recurso        0
Código Município IBGE                     0
Município                                 0
Código UF IBGE                            0
UF                                        0
Região                                    0
Código Função                             0
Nome Função                               0
Código Subfunção                          0
Nome Subfunção                            0
Código Programa                           0
Nome Programa                             0
Código Ação                               0
Nome Ação                                 0
Código Plano Orçamentário                 0
Nome Plano Orçamentário                   0
Valor Empenhado                           0
Valor Liquidado                           0
Valor Pago                                0
Valor Restos A Pagar Inscritos            0
Valor Restos A Pagar Cancelados           0
Valor Restos A Pagar Pagos                0
Código da Emenda_1                        0
dtype: int64

## 9) Preencha os valores nulos da coluna `codigo do autor` com **-1** e os valores nulos da coluna `nome do autor da emenda` com "desconhecido" e confirme que não restaram nulos nessa coluna.

In [31]:
df['Código do Autor da Emenda'] = df['Código do Autor da Emenda'].fillna(-1)
df['Nome do Autor da Emenda'] = df['Nome do Autor da Emenda'].fillna('desconhecido')

## 10) Verifique o tipo da coluna `Ano da Emenda`. Converta-a para **string** (`str`). Mostre o tipo antes e depois da conversão.

In [33]:
df['Ano da Emenda'] = df['Ano da Emenda'].astype(str)

## 11) Converta a coluna `Valor Empenhado` para o tipo **float** (caso ainda não seja). Mostre o tipo após a conversão.

In [34]:
df.info

<bound method DataFrame.info of       Código da Emenda Ano da Emenda  \
0       Sem informação          2014
1       Sem informação          2014
2       Sem informação          2014
3       Sem informação          2014
4       Sem informação          2014
...                ...           ...
88654     201811420017          2018
88655     201827690001          2018
88656     201827690002          2018
88657     201827690003          2018
88658     201827690004          2018

                                          Tipo de Emenda  \
0      Emenda Individual - Transferências com Finalid...
1      Emenda Individual - Transferências com Finalid...
2      Emenda Individual - Transferências com Finalid...
3      Emenda Individual - Transferências com Finalid...
4      Emenda Individual - Transferências com Finalid...
...                                                  ...
88654  Emenda Individual - Transferências com Finalid...
88655  Emenda Individual - Transferências com Finalid...
88656  Emenda Individual - Transferências com Finalid...
88657  Emenda Individual - Transferências com Finalid...
88658  Emenda Individual - Transferências com Finalid...

       Código do Autor da Emenda Nome do Autor da Emenda Número da emenda  \
0                           -1.0            desconhecido              S/I
1                           -1.0            desconhecido              S/I
2                           -1.0            desconhecido              S/I
3                           -1.0            desconhecido              S/I
4                           -1.0            desconhecido              S/I
...                          ...                     ...              ...
88654                     1142.0              ZE GERALDO               17
88655                     2769.0                ZE SILVA                1
88656                     2769.0                ZE SILVA                2
88657                     2769.0                ZE SILVA                3
88658                     2769.0                ZE SILVA                4

      Localidade de aplicação do recurso Código Município IBGE  \
0                          ALVORADA - RS               4300604
1              SANTA ISABEL DO PARÁ - PA               1506500
2                      BARRA BONITA - SC               4202099
3                        ARARAQUARA - SP               3503208
4                       CAMPO LARGO - PR               4104204
...                                  ...                   ...
88654                          PARÁ (UF)        Sem informação
88655                           MÚLTIPLO        Sem informação
88656                       ITURAMA - MG               3134400
88657                       ITURAMA - MG               3134400
88658                  POUSO ALEGRE - MG               3152501

                  Município  Código UF IBGE  ...  \
0                  ALVORADA         4300000  ...
1      SANTA ISABEL DO PARÁ         1500000  ...
2              BARRA BONITA         4200000  ...
3                ARARAQUARA         3500000  ...
4               CAMPO LARGO         4100000  ...
...                     ...             ...  ...
88654        Sem informação         1500000  ...
88655              Múltiplo         3100000  ...
88656               ITURAMA         3100000  ...
88657               ITURAMA         3100000  ...
88658          POUSO ALEGRE         3100000  ...

                                               Nome Ação  \
0      APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...
1           APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA
2      ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...
3           APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA
4      ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...
...                                                  ...
88654  CONSTRUCAO E AMPLIACAO DE UNIDADES OPERACIONAI...
88655  ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...
88656  APOIO A PROJETOS DE DESENVOLVIMENTO SUSTENTAVE...
88657  ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...
88658  APOIO A REALIZACAO DE EVENTOS DE ESPORTE AMADO...

      Código Plano Orçamentário  \
0                             0
1                             0
2                             0
3                             0
4                             0
...                         ...
88654                      EIND
88655                      EIND
88656                      EIND
88657                      EIND
88658                      EIND

                                 Nome Plano Orçamentário Valor Empenhado  \
0      APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...       700000.00
1      APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...       487500.00
2      ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...       100000.00
3      APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...       243750.00
4      ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...      1658333.94
...                                                  ...             ...
88654                                  EMENDA INDIVIDUAL       500000.00
88655                                  EMENDA INDIVIDUAL       499975.00
88656                                  EMENDA INDIVIDUAL       200000.00
88657                                  EMENDA INDIVIDUAL       199970.00
88658                                  EMENDA INDIVIDUAL       100000.00

      Valor Liquidado Valor Pago Valor Restos A Pagar Inscritos  \
0                 0.0        0.0                            0.0
1                 0.0        0.0                            0.0
2                 0.0        0.0                            0.0
3                 0.0        0.0                            0.0
4                 0.0        0.0                            0.0
...               ...        ...                            ...
88654             0.0        0.0                            0.0
88655        499975.0   499975.0                            0.0
88656             0.0        0.0                        11058.0
88657        199970.0   199970.0                            0.0
88658             0.0        0.0                            0.0

      Valor Restos A Pagar Cancelados Valor Restos A Pagar Pagos  \
0                           690900.00                    9100.00
1                           487500.00                       0.00
2                                0.00                  100000.00
3                           243750.00                       0.00
4                           527200.00                 1131133.94
...                               ...                        ...
88654                       369387.36                  130612.64
88655                            0.00                       0.00
88656                            0.00                  188942.00
88657                            0.00                       0.00
88658                         6617.47                   93382.53

      Código da Emenda_1
0         Sem informação
1         Sem informação
2         Sem informação
3         Sem informação
4         Sem informação
...                  ...
88654       201811420017
88655       201827690001
88656       201827690002
88657       201827690003
88658       201827690004

[88659 rows x 29 columns]>

## 12) Calcule o **total** de `Valor Pago` por **Região**. Quais são as duas regiões que mais receberam recursos?

In [36]:
df_regiao = df.groupby('Região')['Valor Pago']
df_regiao

## 13) Calcule a **quantidade** de emendas por **Nome Função**. Mostre as 5 funções com mais emendas.

In [38]:
em_nome_func = df.groupby('Nome Função')['Código da Emenda'].count().sort_values(ascending=False)
em_nome_func.head()

Nome Função
SAÚDE                 37068
URBANISMO              8663
EDUCAÇÃO               8108
AGRICULTURA            4940
ENCARGOS ESPECIAIS     4610
Name: Código da Emenda, dtype: int64

## 14) Crie uma nova coluna chamada `Saldo a Pagar`. Ela deve ser o resultado da subtração entre a coluna `Valor Empenhado` e a coluna `Valor Pago`. Mostre as 5 primeiras linhas apenas com essas três colunas.

In [50]:
df['Saldo a Pagar'] = df['Valor Empenhado'] - df['Valor Pago']
df['Saldo a Pagar'].head()

0     700000.00
1     487500.00
2     100000.00
3     243750.00
4    1658333.94
Name: Saldo a Pagar, dtype: float64

## 15) Elimine a(s) coluna(s) do dataframe que eestá totalmente vazia.

In [43]:
df = df.drop(columns=['Código da Emenda_1'])

## 16) Para finalizar, salve o DataFrame transformado em um arquivo no formato JSON.

In [48]:
df.to_json('df_transformado.json', index=False )